apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-authors
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-authors
  template:
    metadata:
      labels:
        app: app-authors
    spec:
      containers:
      - name: app-authors
        image: domeviz/app_authors
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: QUARKUS_DATASOURCE_USERNAME
            value: dome
          - name: QUARKUS_DATASOURCE_PASSWORD
            value: xrLwmJ2vKcwSPglXTSVYfNdxvbgmXbAA
          - name: QUARKUS_DATASOURCE_JDBC_URL
            value: jdbc:postgresql://dpg-cqcttnuehbks73bln7h0-a.oregon-postgres.render.com/distribuida_06qg
          - name : QUARKUS_HTTP_PORT
            value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: app-authors-service
spec:
  type: ClusterIP
  selector:
    app: app-authors
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
