rootProject.name = "Programacion Distribuida"
include("ejemplo01_cdi")
include("ejemplo02_jpa")
include("ejemplo03_rest")
include("ejemplo03_spring")
include("ejemplo05_quarkus")
include("ejemplo05_autores")
include("ejemplo05_quarkus2")
include("app_authors")
include("app_books")